// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using capstone.Data;

namespace capstone.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200312035926_DropStudentAgain")]
    partial class DropStudentAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("capstone.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("capstone.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Elementary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HighSchool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HigherEducation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MiddleSchool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreSchool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Resource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 25,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "AllinOneHighSchool",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://allinonehighschool.com/"
                        },
                        new
                        {
                            Id = 20,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "CarnagieMellonOpenLearning",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "http://oli.cmu.edu/independent-learner-courses/"
                        },
                        new
                        {
                            Id = 21,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "MITOpenCourseware",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://ocw.mit.edu/indeTrue.htm"
                        },
                        new
                        {
                            Id = 22,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "UCBerkeleyFreeOnline",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.classcentral.com/university/berkeley"
                        },
                        new
                        {
                            Id = 23,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "YaleOpenCourses",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://oyc.yale.edu/"
                        },
                        new
                        {
                            Id = 24,
                            Category = "all",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "HarvardETruetensionSchool",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.eTruetension.harvard.edu/open-learning-initiative"
                        },
                        new
                        {
                            Id = 19,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademyKids",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://learn.khanacademy.org/khan-academy-kids/"
                        },
                        new
                        {
                            Id = 17,
                            Category = "all",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "AllinOneHomeschool",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://allinonehomeschool.com/"
                        },
                        new
                        {
                            Id = 18,
                            Category = "all",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "FreeEdDotNet",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.waybuilder.net/free-ed/AcademicCatalog.asp"
                        },
                        new
                        {
                            Id = 5,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "ChristianLiberty",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.shopchristianliberty.com/"
                        },
                        new
                        {
                            Id = 6,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "BJUPress",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.bjupresshomeschool.com/content/home"
                        },
                        new
                        {
                            Id = 7,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "AlphaOmegaPress",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.aop.com/"
                        },
                        new
                        {
                            Id = 8,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Sonlight",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.sonlight.com/"
                        },
                        new
                        {
                            Id = 9,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Abeka",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.abeka.com/"
                        },
                        new
                        {
                            Id = 4,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "FreeMicrosoftlearningapps",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://www.microsoft.com/en-us/search/shop/apps?q=apps&category=Education"
                        },
                        new
                        {
                            Id = 1,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "OTruefordPodcasts",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "http://podcasts.oTrue.ac.uk/series"
                        },
                        new
                        {
                            Id = 10,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "HackingSTEMLibrary",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://www.microsoft.com/en-us/education/education-workshop/activity-library.aspTrue"
                        },
                        new
                        {
                            Id = 11,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "TeTrueasHomeSchoolCoalition",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://thsc.org/"
                        },
                        new
                        {
                            Id = 12,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "TEDEd",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://ed.ted.com/"
                        },
                        new
                        {
                            Id = 13,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "StanfordOnline",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://online.stanford.edu/"
                        },
                        new
                        {
                            Id = 14,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "codeacademy",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://www.codecademy.com/"
                        },
                        new
                        {
                            Id = 15,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "OpenCulture",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "http://www.openculture.com/freeonlinecourses"
                        },
                        new
                        {
                            Id = 16,
                            Category = "all",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "iTunesU",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://apps.apple.com/ca/app/itunes-u/id490217893"
                        },
                        new
                        {
                            Id = 2,
                            Category = "all",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Whyville",
                            PreSchool = true,
                            Resource = true,
                            Type = "onlineonline",
                            WebSite = "http://www.whyville.net/smmk/nice"
                        },
                        new
                        {
                            Id = 3,
                            Category = "all",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Funbrain",
                            PreSchool = true,
                            Resource = true,
                            Type = "onlineonline",
                            WebSite = "https://www.funbrain.com/"
                        },
                        new
                        {
                            Id = 38,
                            Category = "english",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KidsLearnSpellingFun",
                            PreSchool = false,
                            Resource = false,
                            Type = "appapp",
                            WebSite = "https://www.microsoft.com/en-us/p/kids-learn-spelling-fun-teaches-500-common-english-words/9nr1pw1s6p6v#activetab=pivot:overviewtab"
                        },
                        new
                        {
                            Id = 35,
                            Category = "english",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademy8thgradereading&Vocab",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/ela/cc-8th-reading-vocab"
                        },
                        new
                        {
                            Id = 34,
                            Category = "english",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyGrammar",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/humanities/grammar"
                        },
                        new
                        {
                            Id = 33,
                            Category = "english",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "edTrueEnglishGrammar&Style",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.edTrue.org/course/english-grammar-and-style"
                        },
                        new
                        {
                            Id = 36,
                            Category = "english",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "CourseraEnglishCompositionI",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.coursera.org/learn/english-composition"
                        },
                        new
                        {
                            Id = 37,
                            Category = "english",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "UdemyEnglishLiterature",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.udemy.com/topic/english-literature/"
                        },
                        new
                        {
                            Id = 32,
                            Category = "english",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademy2ndgradereading&Vocab",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/ela/cc-2nd-reading-vocab"
                        },
                        new
                        {
                            Id = 30,
                            Category = "english",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "OldFashionedEducationFairytales",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "http://oldfashionededucation.com/fairytales.htm"
                        },
                        new
                        {
                            Id = 31,
                            Category = "science",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "OldFashionedEducationScience&Nature",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "http://oldfashionededucation.com/science.htm"
                        },
                        new
                        {
                            Id = 29,
                            Category = "english",
                            Elementary = true,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "BibleStudyTools",
                            PreSchool = true,
                            Resource = false,
                            Type = "appapp",
                            WebSite = "https://www.microsoft.com/en-us/p/bible-study-tools-audio-video/9nblggh64sqh?activetab=pivot:overviewtab"
                        },
                        new
                        {
                            Id = 27,
                            Category = "english",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "RosettaStone",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.rosettastone.com/"
                        },
                        new
                        {
                            Id = 26,
                            Category = "english",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "MemRise",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://www.memrise.com/"
                        },
                        new
                        {
                            Id = 28,
                            Category = "english",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Ambleside",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://www.amblesideonline.org/"
                        },
                        new
                        {
                            Id = 45,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyPreAlgebra",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/math/pre-algebra"
                        },
                        new
                        {
                            Id = 49,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademyHighSchoolMath",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/math/high-school-math"
                        },
                        new
                        {
                            Id = 44,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "AlisonCoreMathSkills",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://alison.com/courses/core-maths-skills"
                        },
                        new
                        {
                            Id = 46,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "edTrueMathEssentials",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.edTrue.org/course/maths-essentials"
                        },
                        new
                        {
                            Id = 47,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "CourseraIntrotoCalculus",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.coursera.org/learn/introduction-to-calculus"
                        },
                        new
                        {
                            Id = 48,
                            Category = "math",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "UdemyGeometry",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.udemy.com/topic/geometry/"
                        },
                        new
                        {
                            Id = 42,
                            Category = "math",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "OldFashionedEducationArithmetic",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "http://oldfashionededucation.com/arithmetic_math.htm"
                        },
                        new
                        {
                            Id = 43,
                            Category = "math",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademyEarlyMath",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/math/early-math"
                        },
                        new
                        {
                            Id = 39,
                            Category = "math",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Apologia",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.apologia.com/"
                        },
                        new
                        {
                            Id = 40,
                            Category = "math",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Miquon",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://miquonmath.com/"
                        },
                        new
                        {
                            Id = 41,
                            Category = "math",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Math-U-See",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.mathusee.com/"
                        },
                        new
                        {
                            Id = 58,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyBiology",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/science/biology"
                        },
                        new
                        {
                            Id = 61,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademyAPPhysics2",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/science/physics/ap-physics-2"
                        },
                        new
                        {
                            Id = 62,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "CourseraPlantsPartI",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.coursera.org/learn/plantknows"
                        },
                        new
                        {
                            Id = 53,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "LearnHTML(5)",
                            PreSchool = false,
                            Resource = false,
                            Type = "appapp",
                            WebSite = "https://www.microsoft.com/en-us/p/learn-html-5/9nblggh31wfj?activetab=pivot:overviewtab"
                        },
                        new
                        {
                            Id = 55,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "C++ProgrammingbyWagmob",
                            PreSchool = false,
                            Resource = false,
                            Type = "appapp",
                            WebSite = "https://www.microsoft.com/en-us/p/c-programming-by-wagmob/9wzdncrdn96h?activetab=pivot:overviewtab"
                        },
                        new
                        {
                            Id = 56,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "ChemistrybyWAGmob",
                            PreSchool = false,
                            Resource = false,
                            Type = "appapp",
                            WebSite = "https://www.microsoft.com/en-us/p/chemistry-by-wagmob/9wzdncrdn317?activetab=pivot:overviewtab"
                        },
                        new
                        {
                            Id = 57,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "UdemyNutrition",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.udemy.com/topic/nutrition/"
                        },
                        new
                        {
                            Id = 59,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "edTrueAppliedHumanAnatomy",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.edTrue.org/course/applied-anatomy-of-the-locomotor-system"
                        },
                        new
                        {
                            Id = 60,
                            Category = "science",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "AcademicEarthChemistry",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://academicearth.org/chemistry/"
                        },
                        new
                        {
                            Id = 54,
                            Category = "science",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyHealth&Medicine",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/science/health-and-medicine"
                        },
                        new
                        {
                            Id = 52,
                            Category = "science",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Apologia",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.apologia.com/"
                        },
                        new
                        {
                            Id = 50,
                            Category = "science",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "CODE",
                            PreSchool = false,
                            Resource = true,
                            Type = "linklink",
                            WebSite = "https://code.org/learn"
                        },
                        new
                        {
                            Id = 51,
                            Category = "science",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "NationalGeographicKids",
                            PreSchool = true,
                            Resource = true,
                            Type = "onlineonline",
                            WebSite = "https://kids.nationalgeographic.com/"
                        },
                        new
                        {
                            Id = 69,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyUSGovernment&Civics",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/humanities/us-government-and-civics"
                        },
                        new
                        {
                            Id = 72,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "KhanAcademyApWorldHistory",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/humanities/ap-world-history"
                        },
                        new
                        {
                            Id = 67,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "CourseraEconomicsofMoney",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.coursera.org/learn/money-banking"
                        },
                        new
                        {
                            Id = 68,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = true,
                            Name = "HilsdaleCollegeFreeCourses",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.hillsdale.edu/educational-outreach/free-online-courses/"
                        },
                        new
                        {
                            Id = 70,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "edTrueIntroductiontoAmericanGovernment",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.edTrue.org/Trueseries/harvardTrue-us-government"
                        },
                        new
                        {
                            Id = 71,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = true,
                            HigherEducation = true,
                            MiddleSchool = false,
                            Name = "UdemyPsychology",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.udemy.com/topic/social-psychology/"
                        },
                        new
                        {
                            Id = 66,
                            Category = "socialstudies",
                            Elementary = true,
                            HighSchool = true,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "KhanAcademyUSHistory",
                            PreSchool = false,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "https://www.khanacademy.org/humanities/us-history"
                        },
                        new
                        {
                            Id = 65,
                            Category = "socialstudies",
                            Elementary = true,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = true,
                            Name = "OldFashionedEducationGeography",
                            PreSchool = true,
                            Resource = false,
                            Type = "onlineonline",
                            WebSite = "http://oldfashionededucation.com/geography.htm"
                        },
                        new
                        {
                            Id = 63,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "Apologia",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "https://www.apologia.com/"
                        },
                        new
                        {
                            Id = 64,
                            Category = "socialstudies",
                            Elementary = false,
                            HighSchool = false,
                            HigherEducation = false,
                            MiddleSchool = false,
                            Name = "BeautifulFeetBooks",
                            PreSchool = false,
                            Resource = true,
                            Type = "booksbooks",
                            WebSite = "http://www.bfbooks.com/"
                        });
                });

            modelBuilder.Entity("capstone.Models.HomeScholar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("English")
                        .HasColumnType("TEXT");

                    b.Property<string>("Math")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Science")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialStudies")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeScholars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            English = "Old Fashioned Education Fairy tales",
                            Math = "Old Fashioned Education Arithmetic",
                            Name = "Jon Smith",
                            Science = "Old Fashioned Education Science & Nature",
                            SocialStudies = "Old Fashioned Education Geography "
                        },
                        new
                        {
                            Id = 2,
                            English = "Khan Academy Grammar",
                            Math = "Alison Core Math Skills",
                            Name = "Bobby Miller",
                            Science = "Khan Academy Biology",
                            SocialStudies = "Hilsdale College Free Courses"
                        },
                        new
                        {
                            Id = 3,
                            English = "Coursera English Composition I",
                            Math = "Udemy Geometry",
                            Name = "Sarah Brooks",
                            Science = "Academic Earth Chemistry",
                            SocialStudies = "edX Introduction to American Government"
                        });
                });

            modelBuilder.Entity("capstone.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sam",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tom",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mary",
                            LastName = "Brooks"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("capstone.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("capstone.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("capstone.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("capstone.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
